---
apiVersion: v1
kind: Secret
metadata:
  name: logs-secret
type: Opaque
data:
  keyid: AKIAVOY7ZHYM4DUE4JVX
  accesskey: 9AK8xfn7YlTRK15n7lY9JT+zDNY7Ph5f7AqmzeqB
  region: us-east-2
  urlnet: http://*:7076